### ISSUE TITLE
Paid consulting

### ISSUE THREAD

**Issue by kuopassa** [HomelessPhD/BTC32#7]
Do you have an email address that I could send a message to? It's related to this BTC32 project.

**Comment by HomelessPhD** [comment]
Sure? The one specified in the article would work - generalizatorSUB@gmail.com

I should admit and notice - its trully bruteforce competition rather than puzzle (beside of the fact someone could call the Elyptic Curve encryption AND\OR private -> public key revert as a big puzzle)
